# Generated by Django 2.1 on 2018-08-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20180811_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datePublic',
            field=models.DateTimeField(blank=True),
        ),
    ]
