# Generated by Django 2.1 on 2018-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20180811_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='urlName',
            field=models.CharField(default='urlName', max_length=30),
            preserve_default=False,
        ),
    ]
