# Generated by Django 2.1 on 2018-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_remove_category_urlname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='urlName',
            field=models.SlugField(default='slugName', max_length=30),
            preserve_default=False,
        ),
    ]
