# Generated by Django 2.1 on 2018-08-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_category_urlname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='collap',
            field=models.TextField(blank=True),
        ),
    ]
